### ISSUE TITLE
Line graph scale issue

### ISSUE THREAD

**Issue by aaronw22** [e61-Institute/theme61#83]
![scale issue](https://github.com/e61-Institute/theme61/assets/44219419/f5ac8567-0398-43d4-a17a-f758080e8c56)

Should run c(2, 4.5, 0.5) rather than 0-5.

**Comment by aaronw22** [comment]
Furthermore, when you manually specify scales then the label does not position itself as nicely. 

Also possibly too much whitespace at the top and bottom?

![qld oo vs invest turnover](https://github.com/e61-Institute/theme61/assets/44219419/64b50274-5de5-400a-a78b-7ea08f8299e9)

**Comment by aaronw22** [comment]
Ooo this didn't work at all.

```
ggplot(diff_w_se_coef[month > "2010-01-01" & month < "2013-01-01"], 
       aes(x = month)) +
  geom_line(aes(y = estimate)) +
  geom_ribbon(aes(ymin = ci_l, ymax = ci_h), alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2011-08-01"), xmax = as.Date("2012-07-01"),
           ymin = -3, ymax = 1,
           fill = "red", alpha = 0.1) +
  add_baseline() +
  # scale_y_continuous_e61(limits = c(-3, 1, 1)) +
  labs_e61(
    title = "Difference in Number of Property Transactions*", 
    subtitle = "Investors less owner-occupiers, monthly**",
    footnotes = c("Red shaded area indicates the time period during which Queensland removed the owner-occupier stamp duty concession.", "Shaded bands indicate 95 per cent confidence intervals."),
    sources = c("PropTrack", "e61 Institute"),
    x = NULL, y = "'000")
  # theme_e61()

save_e61("output/diff in oo and investor sales with se.svg")
```

![diff in oo and investor sales with se](https://github.com/e61-Institute/theme61/assets/44219419/9f1bdbc8-9e54-4a11-a9fd-a5c0981772e0)

**Comment by JackBuckley** [comment]
These should now both be solved on the latest version of dev.
